<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="MONSTER-IDEAPAD5" failures="1" tests="6" name="Default test(failed)" time="47.432" errors="0" timestamp="2024-06-18T16:57:05 IST">
  <testcase classname="practiceTestFromTestNG.SampleInvoiceTestwithRetryAnalyzer" name="createInvoiceTest" time="0.062">
    <skipped/>
  </testcase> <!-- createInvoiceTest -->
  <testcase classname="practiceTestFromTestNG.SampleInvoiceTestwithRetryAnalyzer" name="createInvoiceTest" time="0.014">
    <skipped/>
  </testcase> <!-- createInvoiceTest -->
  <testcase classname="practiceTestFromTestNG.SampleInvoiceTestwithRetryAnalyzer" name="createInvoiceTest" time="0.053">
    <skipped/>
  </testcase> <!-- createInvoiceTest -->
  <testcase classname="practiceTestFromTestNG.SampleInvoiceTestwithRetryAnalyzer" name="createInvoiceTest" time="0.009">
    <skipped/>
  </testcase> <!-- createInvoiceTest -->
  <testcase classname="practiceTestFromTestNG.SampleInvoiceTestwithRetryAnalyzer" name="createInvoiceTest" time="0.059">
    <skipped/>
  </testcase> <!-- createInvoiceTest -->
  <testcase classname="practiceTestFromTestNG.SampleInvoiceTestwithRetryAnalyzer" name="createInvoiceTest" time="0.024">
    <failure type="java.lang.AssertionError" message="expected [login] but found [Administrator - Home - vtiger CRM 5 - Commercial Open Source CRM]">
      <![CDATA[java.lang.AssertionError: expected [login] but found [Administrator - Home - vtiger CRM 5 - Commercial Open Source CRM]
at practiceTestFromTestNG.SampleInvoiceTestwithRetryAnalyzer.createInvoiceTest(SampleInvoiceTestwithRetryAnalyzer.java:14)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- createInvoiceTest -->
  <testcase classname="practiceTestFromTestNG.SampleInvoiceTestwithRetryAnalyzer" name="createInvoiceWithContacts" time="0.0">
    <ignored/>
  </testcase> <!-- createInvoiceWithContacts -->
</testsuite> <!-- Default test(failed) -->
